### ISSUE TITLE
功能挺好部署方便,说说开发给你一个思路

### ISSUE THREAD

**Issue by Hi-MrZeFr** [ESHexoN/ESHexoN#2]
说说的后端只需要提供一个数据支持,然后前端我可以简单帮写个简陋的js,或者自己造

**Comment by ocoke** [comment]
现在是这样的，后端提供了全部的 API 支持。您可以[查看我们的文档](https://eshexon.js.cool)。

您可以选择自己构建前端，也可以查看我们的[官方前端](https://github.com/ESHexoN/eshexon-frontend)。

**Comment by Hi-MrZeFr** [comment]
还可以吧,说说做后端搞个API,提供数据,前端简单点写啦

**Comment by ocoke** [comment]
说说近期不会实现，目前的想法是通过 [oCoke/detalk](https://github.com/oCoke/detalk) 特定的 `PAGE_ID` 实现（如 `@TALK`）

未来 ESHexoN 将接入 Detalk 管理面板。
