### ISSUE TITLE
公共前端加载速度慢

### ISSUE THREAD

**Issue by lfyszy** [ESHexoN/ESHexoN#4]
一直在注册那转，注册不起

**Comment by ocoke** [comment]
我们很抱歉，但是 ESHexoN 目前应该是遇到 Breaking Changes 了。这个问题需要修复

**Comment by gittyspirit** [comment]
到现在都还没有解决，我后端早早部署好了，就等前端了呀

**Comment by ocoke** [comment]
@gittyspirit 现在前端已经修复了！感谢）
